package signature

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"testing"
)

func TestSignRoundTrip(t *testing.T) {
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	body := []byte(`{}`)
	sig := Sign(priv, "POST", "/v1/connect/workspace-1", 1_700_000_000_000, body)

	sigBytes, err := base64.StdEncoding.DecodeString(sig)
	if err != nil {
		t.Fatal(err)
	}
	if !ed25519.Verify(pub, SigningPayload("POST", "/v1/connect/workspace-1", 1_700_000_000_000, body), sigBytes) {
		t.Fatal("expected signature to verify against the same payload")
	}
}

func TestSignRejectsOnTamperedBody(t *testing.T) {
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	sig := Sign(priv, "POST", "/path", 1, []byte("original"))
	sigBytes, err := base64.StdEncoding.DecodeString(sig)
	if err != nil {
		t.Fatal(err)
	}
	if ed25519.Verify(pub, SigningPayload("POST", "/path", 1, []byte("tampered")), sigBytes) {
		t.Fatal("expected signature over a different body to fail verification")
	}
}

// TestSigningPayloadMatchesTypeScript pins the exact same expected string
// the control plane's own conformance test pins,
// generated by actually running its request-signing scheme's
// signingPayload() equivalent — since the format is a pure function of its inputs, an
// independent Go implementation producing the same bytes for the same
// inputs is real cross-language proof, not a restated assumption.
func TestSigningPayloadMatchesTypeScript(t *testing.T) {
	const want = "POST\n/v1/nodes/node-1/tailnet\n1700000000000\n" +
		"ed54f979649538b52f3ff849f38803875e526ec6457eb4c27e10e87e2734dd1d"

	got := SigningPayload("POST", "/v1/nodes/node-1/tailnet", 1_700_000_000_000, []byte(`{"nodeKey":"nodekey:abc"}`))
	if string(got) != want {
		t.Fatalf("signing payload diverges from the TypeScript reference:\n got:  %q\n want: %q", got, want)
	}
}
